name: 'ci'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
jobs:
  ci:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [12.x, 14.x, 16.x, 18.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - if: matrix.os == 'windows-latest'
        run: npm install --global --production windows-build-tools
      - run: npm run clean
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - run: npm run test
